DEFAULT_CONFIG = {
    "architecture": "motionBert",
    "dataset": "Skeleton Newton",
    "epochs": 32,
    'warmup_ratio': 0.03,
    "labels": ['age', 'hr_bpm', 'eA1C', 'Attention Deficit Disorder (ADHD)', 'bmi', 'gender'],
    "task_types": ["reg", "clas", "reg", "clas"],#, "reg", 'reg'],
    "batch_size": 16,
    "eval_batch_size": 16,
    "learning_rate": 0.0004,
    "size_seq": 256,
    "use_slicing": False,
    "lambda_scale": 0.0,
    "lambda_3d_velocity": 0.0,
    "lambda_quat": 0.5,
    "lambda_ko_leo_loss": 0.1,
    "adamw_weight_decay": 0.01,
    "dim_representation": 64,
    "dim_feat": 256,
    "num_heads": 8,
    "depth": 5,
    "scheduler_type": "Annealing",
    "dropout_ratio": 0.1,
    "modality_dropout_prob": 0.3,
    "group_masking": True,
    "time_normalize": True,
    "space_normalize": True,
    'span_group_masking': 16,
    "amount_device": 1,
    "use_scaler": True,
    "use_compile": True,
    "use_matmul": True,
    "model_file": "",
    "load_model_epoch": -1,
    "training_type": "scratch",
    "mlp_start": False,
    "mask_loss": False,
    "with_noise": True,
    "with_rope": True,
    "use_flash_attn": False,
    "use_angular": False,
    "visualize_attention_maps": True,
    "attention_samples_per_activity": 1,
    "final_eval_compute_silhouette": True,
    "final_eval_umap_view": True,
    "debug_mode": False,
    "use_block_embedding": True,
    "num_sink_tokens": 0,
}


LONG_CONFIG = {
    "architecture": "motionBert",
    "dataset": "Skeleton Newton",
    "name": "Long Seq - New people sink no attend",
    "epochs": 32,
    'warmup_ratio': None,
    'warmup_epochs': 0.3,
    "labels": ["age", "hr_bpm", "eA1C", "bmi", "gender", "wearable_total_weekly_hours", "Anxiety", "Depression"],
    "task_types": ["reg", "reg", "reg", "reg", "clas", "reg", "clas", "clas"],
    "batch_size": 8,
    "eval_batch_size": 8,
    "learning_rate": 0.0008,
    "size_seq": 900,
    "use_slicing": False,
    "lambda_scale": 0.0,
    "lambda_3d_velocity": 0.1,
    "lambda_quat": 0.0,
    "lambda_ko_leo_loss": 0.0,
    "adamw_weight_decay": 0.01,
    "dim_representation": 32,
    "dim_feat": 128,
    "num_heads": 8,
    "depth": 8,
    "scheduler_type": "Annealing",
    "dropout_ratio": 0.1,
    "modality_dropout_prob": 0.3,
    "group_masking": 4,
    "time_normalize": False,
    "space_normalize": False,
    "random_masking": 0.01,
    "random_masking_frames": 0.01,
    "span_group_masking": 16,
    "amount_device": 1,
    "use_scaler": True,
    "use_compile": True,
    "use_matmul": True,
    "model_file": "",
    "load_model_epoch": -1,
    "training_type": "scratch",
    "mlp_start": False,
    "mask_loss": False,
    "with_noise": True,
    "with_rope": True,
    "use_flash_attn": True,
    "use_angular": False,
    "visualize_attention_maps": True,
    "attention_samples_per_activity": 1,
    "final_eval_compute_silhouette": True,
    "final_eval_umap_view": True,
    "debug_mode": False,
    "use_block_embeddings": True,
    "noise_std": 0.05,
    "len_cycle": 128,
    "len_sts_cycle": 128,
    "seq_per_person": 2,
    "limit_users": -1,
    "equal_seq_per_activity": True,
    "centroid_type": "second",
    "num_sink_tokens": 2,
}

SHORT_CONFIG = {
    "architecture": "motionBert",
    "dataset": "Skeleton Newton",
    "name": "Short Seq - New people sink no attend",
    "epochs": 40,
    'warmup_ratio': None,
    'warmup_epochs': 0.3,
    "labels": ["age", "hr_bpm", "eA1C", "bmi", "gender", "wearable_total_weekly_hours", "Anxiety", "Depression"],
    "task_types": ["reg", "reg", "reg", "reg", "clas", "reg", "clas", "clas"],
    "batch_size": 112,  # Reduced from 128 to accommodate sink tokens with torch.compile
    "eval_batch_size": 64,
    "learning_rate": 0.0008,
    "size_seq": 128,
    "use_slicing": False,
    "lambda_scale": 0.0,
    "lambda_3d_velocity": 0.0,
    "lambda_quat": 0.5,
    "lambda_ko_leo_loss": 0.0,
    "adamw_weight_decay": 0.01,
    "dim_representation": 16,
    "dim_feat": 128,
    "num_heads": 8,
    "depth": 5,
    "scheduler_type": "Annealing",
    "dropout_ratio": 0.1,
    "modality_dropout_prob": 0.3,
    "group_masking": 4,
    "random_masking": 0.02,
    "random_masking_frames": 0.04,
    "time_normalize": True,
    "space_normalize": True,
    "span_group_masking": 32,
    "amount_device": 1,
    "use_scaler": True,
    "use_compile": True,
    "use_matmul": True,
    "model_file": "",
    "load_model_epoch": -1,
    "training_type": "scratch",
    "mlp_start": False,
    "mask_loss": False,
    "with_noise": True,
    "with_rope": True,
    "use_flash_attn": True,
    "use_angular": False,
    "visualize_attention_maps": True,
    "attention_samples_per_activity": 1,
    "final_eval_compute_silhouette": True,
    "final_eval_umap_view": True,
    "debug_mode": False,
    "use_block_embeddings": True,
    "noise_std": 0.05,
    "len_cycle": 128,
    "len_sts_cycle": 128,
    "seq_per_person": 30,
    "limit_users": -1,
    "equal_seq_per_activity": True,
    "centroid_type": "second",
    "seq_overlap": 0,
    "num_sink_tokens": 1,
}


LIKE_OLD_CONFIG = {
    "architecture": "motionBert",
    "dataset": "Skeleton Newton",
    "name": "256 no group",
    "epochs": 20,
    'warmup_ratio': None,
    'warmup_epochs': 1,
    "labels": ["age", "hr_bpm", "eA1C", "Attention Deficit Disorder (ADHD)", "bmi", "gender", "wearable_total_weekly_hours", "B12 deficiency", 'Depression'],
    "task_types": ["reg", "reg", "reg", "clas", "reg", "clas", "reg", "clas", "clas"],
    "batch_size": 32,
    "eval_batch_size": 32,
    "learning_rate": 0.0008,
    "size_seq": 256,
    "use_slicing": False,
    "lambda_scale": 0.1,
    "lambda_3d_velocity": 0.1,
    "lambda_quat": 0.5,
    "lambda_ko_leo_loss": 0.0,
    "adamw_weight_decay": 0.01,
    "dim_representation": 16,
    "dim_feat": 128,
    "num_heads": 8,
    "depth": 5,
    "scheduler_type": "Annealing",
    "dropout_ratio": 0.1,
    "modality_dropout_prob": 0.3,
    "group_masking": 0,
    "random_masking": 0.25,
    "frame_masking": 0.1,
    "time_normalize": False,
    "space_normalize": False,
    "span_group_masking": 16,
    "amount_device": 1,
    "use_scaler": True,
    "use_compile": True,
    "use_matmul": True,
    "model_file": "",
    "load_model_epoch": -1,
    "training_type": "scratch",
    "mlp_start": False,
    "mask_loss": False,
    "with_noise": True,
    "with_rope": True,
    "use_flash_attn": True,
    "use_angular": False,
    "visualize_attention_maps": True,
    "attention_samples_per_activity": 1,
    "final_eval_compute_silhouette": True,
    "final_eval_umap_view": True,
    "debug_mode": False,
    "use_block_embeddings": True,
    "noise_std": 0.05,
    "len_cycle": 128,
    "len_sts_cycle": 128,
    "seq_per_person": 8,
    "limit_users": -1,
    "equal_seq_per_activity": True,
    "centroid_type": "second",
    "num_sink_tokens": 0,
}